﻿version: '3'
sservices:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ElxpmwowGfv451200"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433" 
  api:
    build:
      context: ../
      dockerfile: ProductOrder.API/Dockerfile
    ports:
      - "8080:80"